### ISSUE TITLE
[Bug]: Fabric 1.4.46 invalid memory address.

### ISSUE THREAD

**Issue by ythefly** [danielmiessler/fabric#1020]
### What happened?

when I do pbpaste | fabric -s -p summarize I keep getting the error below. This happens with any other patterns. It works fine before 1.4.46. Below is a summary of the output of the error: 

### Version check

- [X] Yes I was.

### Relevant log output

```shell
   ~ ························································· 0|2 ✘  08:36:45 
❯ pbpaste | fabric -s -p summarize
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x100d737f8]

goroutine 1 [running]:
github.com/danielmiessler/fabric/db.(*Session).Append(...)
	/Users/jackieshum/go/pkg/mod/github.com/danielmiessler/fabric@v1.4.46/db/sessions.go:47
github.com/danielmiessler/fabric/core.(*Chatter).Send(0x140004bf4d0, 0x140001a8de0, 0x140004b8780)
	/Users/jackieshum/go/pkg/mod/github.com/danielmiessler/fabric@v1.4.46/core/chatter.go:61 +0x2a8
github.com/danielmiessler/fabric/cli.Cli({0x100d7deff, 0x7})
	/Users/jackieshum/go/pkg/mod/github.com/danielmiessler/fabric@v1.4.46/cli/cli.go:211 +0x5e0
main.main()
	/Users/jackieshum/go/pkg/mod/github.com/danielmiessler/fabric@v1.4.46/main.go:12 +0x2c
```

**Comment by eugeis** [comment]
Thanks.

Fixed in https://github.com/danielmiessler/fabric/releases/tag/v1.4.48
