### ISSUE TITLE
[Bug]: Hitting SIGSEV when using OpenRouter vendor

### ISSUE THREAD

**Issue by ruihangdu** [danielmiessler/fabric#1026]
### What happened?

fabric version: v1.4.52
vendor: OpenRouter
runtime options:
```
Options:
Model: google/gemini-flash-1.5-8b-exp
Temperature: 0.700000
TopP: 0.900000
PresencePenalty: 0.000000
FrequencyPenalty: 0.000000
```
command ran:
```
fabric -y "https://youtu.be/y-hSsqQfM2I\?si\=BROougUb1cXwXBa9" --pattern extract_wisdom
```
Error message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4596154]

goroutine 1 [running]:
github.com/danielmiessler/fabric/db.(*Session).Append(...)
        /<redacted path>/fabric/db/sessions.go:49
github.com/danielmiessler/fabric/core.(*Chatter).Send(0xc0000ade60, 0xc00023ed20, 0xc000064040)
        /<redacted path>/fabric/core/chatter.go:57 +0x3f4
github.com/danielmiessler/fabric/cli.Cli({0x45a1d1b, 0x7})
        /<redacted path>/fabric/cli/cli.go:211 +0x80c
main.main()
        /<redacted path>/fabric/main.go:12 +0x25
```

### Version check

- [X] Yes I was.

**Comment by ruihangdu** [comment]
Forgot to mention that I also see error message `SiliconCloud error, status code: 401, message: json: cannot unmarshal string into Go value of type openai.ErrorResponse` with every command I ran. Not sure if should create a separate bug for that.
