### ISSUE TITLE
[Bug]: pbpaste piping does not work for fabric 1.4.52

### ISSUE THREAD

**Issue by ythefly** [danielmiessler/fabric#1027]
### What happened?

when I run this command pbpaste | fabric -s -p summarize, I get the following error below. It seems like the 1.4.5 updates has bad connections using pbpaste. If I use an alias like:  alias extractwisdom='echo "$(pbpaste)" | fabric -s -p extract_wisdom'. It would work fine.  I don't know why. Here is the error output: 

### Version check

- [X] Yes I was.

### Relevant log output

```shell
   ~ ··························································································
    ~ ············································································· 23:48:50 
❯ pbpaste | fabric -s -p summarize
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x101283878]

goroutine 1 [running]:
github.com/danielmiessler/fabric/db.(*Session).Append(...)
	/Users/jackieshum/go/pkg/mod/github.com/danielmiessler/fabric@v1.4.52/db/sessions.go:49
github.com/danielmiessler/fabric/core.(*Chatter).Send(0x140004cf8c0, 0x1400045dc70, 0x140004b6a00)
	/Users/jackieshum/go/pkg/mod/github.com/danielmiessler/fabric@v1.4.52/core/chatter.go:57 +0x328
github.com/danielmiessler/fabric/cli.Cli({0x10128e79f, 0x7})
	/Users/jackieshum/go/pkg/mod/github.com/danielmiessler/fabric@v1.4.52/cli/cli.go:211 +0x630
main.main()
	/Users/jackieshum/go/pkg/mod/github.com/danielmiessler/fabric@v1.4.52/main.go:12 +0x2c
```

**Comment by eugeis** [comment]
fixed in  v1.4.53
