### ISSUE TITLE
[Bug]: fabric --setup fails

### ISSUE THREAD

**Issue by cleesmith** [danielmiessler/fabric#211]
### What happened?

(fabric) cleesmith:~$ fabric --setup  fails ModuleNotFoundError: No module named 'dotenv'

MacBook Pro macOS Sonoma 14.3.1 

The error happens using anaconda and conda activate to keep python packages separate.
It also happens without using anaconda ... although i would prefer using conda since i test lots python AI code.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
pipx install .
installed package fabric 0.2.0, installed using Python 3.12.1
  These apps are now globally available
    - fabric
    - fabric-api
    - fabric-webui
    - ts
    - yt
done! ✨ 🌟 ✨

(fabric) cleesmith:~$ fabric --setup
Traceback (most recent call last):
  File "/Users/cleesmith/.local/bin/fabric", line 7, in <module>
    from installer import cli
  File "/Users/cleesmith/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/__init__.py", line 1, in <module>
    from .client.cli import main as cli
  File "/Users/cleesmith/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/client/cli/__init__.py", line 1, in <module>
    from .fabric import main
  File "/Users/cleesmith/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/client/cli/fabric.py", line 1, in <module>
    from .utils import Standalone, Update, Setup, Alias
  File "/Users/cleesmith/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/client/cli/utils.py", line 8, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

... and pipx install dotenv and pip install dotenv also fail.
```

**Comment by nicolas-g** [comment]
FYI I have the exact same issue, also tried to install  "python-dotenv" and  "python-dotenv[cli]" with no luck ..

**Comment by springyuniverse** [comment]
I had the same issue and solved by the following: 

`pipx inject fabric python-dotenv`  and I found also the JWT was missing so I also did 
'pipx inject fabric jwt' and worked with no issue

**Comment by xssdoctor** [comment]
Fixing now. Hold on

**Comment by cleesmith** [comment]
well i tried the pipx inject's and got this:
fabric --setup
Traceback (most recent call last):
  File "/Users/cleesmith/.local/bin/fabric", line 7, in <module>
    from installer import cli
  File "/Users/cleesmith/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/__init__.py", line 2, in <module>
    from .server import (
  File "/Users/cleesmith/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/server/__init__.py", line 2, in <module>
    from .api import main as run_api_server
  File "/Users/cleesmith/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/server/api/__init__.py", line 1, in <module>
    from .fabric_api_server import main
  File "/Users/cleesmith/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/server/api/fabric_api_server.py", line 4, in <module>
    from flask import Flask, request, jsonify
ModuleNotFoundError: No module named 'flask'

**Comment by xssdoctor** [comment]
Fixed

**Comment by cleesmith** [comment]
Completely started over again and now the install succeeded, even after a conda activate fabric (for python 10).
But i always have to do a: pipx install . --force ... as if the installation is happening outside the conda environment, which is kind of worrying.
But thanks for the quit fix.

**Comment by nicolas-g** [comment]
working now for me too, thanks for the quick fix

**Comment by danielmiessler** [comment]
Fixed, thank you everyone. Especially @xssdoctor !
