### ISSUE TITLE
[Bug]: --changeDefaultModel & --clear throwing errors

### ISSUE THREAD

**Issue by arcaneum** [danielmiessler/fabric#252]
### What happened?

This is related to a series of previous issues post the latest pipx upgrade that we were discussing via a separate bug report. Opening a new report as suggested by @danielmiessler for couple of issues that still persist. 

Please can you have a look? I'm on an Apple Silicon M3 Max machine and running this inside a Conda virtual env.

### 1. --changeDefaultModel throws an error

```
(base) <<>>@MacBook-Pro fabric % fabric --changeDefaultModel gpt-4-turbo-preview
Traceback (most recent call last):
  File "/Users/<<>>/.local/bin/fabric", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/<<>>/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/client/cli/fabric.py", line 80, in main
    Setup().default_model(args.changeDefaultModel)
  File "/Users/<<>>/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/client/cli/utils.py", line 537, in default_model
    standalone = Standalone(args=[], pattern="")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<<>>/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/client/cli/utils.py", line 49, in __init__
    if args.model:
       ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'model'

```

### 2. --clear not recognised

```
(base) <<>>@MacBook-Pro fabric % fabric --clear
usage: fabric [-h] [--text TEXT] [--copy] [--agents {trip_planner,ApiKeys}] [--output [OUTPUT]]
              [--stream] [--list] [--update] [--pattern PATTERN] [--setup]
              [--changeDefaultModel CHANGEDEFAULTMODEL] [--model MODEL] [--listmodels]
              [--remoteOllamaServer REMOTEOLLAMASERVER] [--context]
fabric: error: unrecognized arguments: --clear

```

### Version check

- [X] Yes I was.

**Comment by xssdoctor** [comment]
--clear is gone. if you want to reset your custom model, just reset it to gpt-4-turbo-preview, that was the default before.

**Comment by xssdoctor** [comment]
never mind. it was broken, youre right. just fixed it. try now

**Comment by ichoosetoaccept** [comment]
I just pulled.
Still get
```
fabric --changeDefaultModel claude-3-opus-20240229
Traceback (most recent call last):
  File "/Users/ismar/.local/bin/fabric", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ismar/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/client/cli/fabric.py", line 80, in main
    Setup().default_model(args.changeDefaultModel)
  File "/Users/ismar/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/client/cli/utils.py", line 537, in default_model
    standalone = Standalone(args=[], pattern="")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ismar/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/client/cli/utils.py", line 49, in __init__
    if args.model:
       ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'model'
```

**Comment by xssdoctor** [comment]
Did you pipx upgrade fabric after you git pulled?

**Comment by ichoosetoaccept** [comment]
I did just now and now it works, then came back here to say so but you were quicker :).
Works, thank you!

**Comment by arcaneum** [comment]
> never mind. it was broken, youre right. just fixed it. try now

Thank you very much @xssdoctor. Everything works perfectly now 👍

**Comment by arcaneum** [comment]
> --clear is gone. if you want to reset your custom model, just reset it to gpt-4-turbo-preview, that was the default before.

Probably just need to clean up the Readme file since --clear is still there as one of the options:

![image](https://github.com/danielmiessler/fabric/assets/38038031/421c8b84-3719-4117-ae65-bfb200e1cb34)
