### ISSUE TITLE
PROXY ERR

### ISSUE THREAD

**Issue by kilopper** [danielmiessler/fabric#255]
### What happened?

```
Traceback (most recent call last):
  File "/home/kali/.local/bin/fabric", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/kali/.local/share/pipx/venvs/fabric/lib/python3.11/site-packages/installer/client/cli/fabric.py", line 101, in main
    standalone = Standalone(args, args.pattern)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/share/pipx/venvs/fabric/lib/python3.11/site-packages/installer/client/cli/utils.py", line 43, in __init__
    self.client = OpenAI(api_key=api_key, base_url=base_url)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/share/pipx/venvs/fabric/lib/python3.11/site-packages/openai/_client.py", line 112, in __init__
    super().__init__(
  File "/home/kali/.local/share/pipx/venvs/fabric/lib/python3.11/site-packages/openai/_base_client.py", line 801, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/share/pipx/venvs/fabric/lib/python3.11/site-packages/httpx/_client.py", line 670, in __init__
    proxy_map = self._get_proxy_map(proxies, allow_env_proxies)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/share/pipx/venvs/fabric/lib/python3.11/site-packages/httpx/_client.py", line 216, in _get_proxy_map
    return {
           ^
  File "/home/kali/.local/share/pipx/venvs/fabric/lib/python3.11/site-packages/httpx/_client.py", line 217, in <dictcomp>
    key: None if url is None else Proxy(url=url)
                                  ^^^^^^^^^^^^^^
  File "/home/kali/.local/share/pipx/venvs/fabric/lib/python3.11/site-packages/httpx/_config.py", line 334, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:7891/')
                                                                            
```

### Version check

- [X] Yes I was.

### Relevant log output

```shell
i use clash on kali linux . it's ok to google.com .  socks port:7891 http-port:7890
```

**Comment by xssdoctor** [comment]
i'll be honest i have no idea what that error is about. try this. first git pull again and then pipx upgrade fabric. Then do fabric --update. make sure your .zshrc doesnt have any weird aliases in it from previous fabric versions. then if that doesnt work, just erase the fabric folder and redownload, delete your .config/fabric folder and re-do everything. I've literally never seen that error and there is no socks proxy used anywhere in the code.
