### ISSUE TITLE
[Bug]:  module 'jwt' has no attribute 'encode'

### ISSUE THREAD

**Issue by sganiere** [danielmiessler/fabric#278]
### What happened?

I'm trying to use the fabric-api, install the whole thing based on instructions, no change on any of the json file in the server folder, however I'm trying to connect via a curl command I have the following error message:

  File "/Users/test1/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/server/api/fabric_api_server.py", line 246, in login
    token = jwt.encode({"username": username}, os.getenv("JWT_SECRET"), algorithm="HS256")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'jwt' has no attribute 'encode'

the curl command I'm using:

curl -d '{"password":"password1","username":"user1"}' -H 'Content-Type: application/json' http://localhost:13337/login

### Version check

- [X] Yes I was.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/test1/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test1/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test1/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test1/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test1/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test1/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/test1/Library/Application Support/pipx/venvs/fabric/lib/python3.12/site-packages/installer/server/api/fabric_api_server.py", line 246, in login
    token = jwt.encode({"username": username}, os.getenv("JWT_SECRET"), algorithm="HS256")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'jwt' has no attribute 'encode'
```

**Comment by danielmiessler** [comment]
I believe this has to do with the versions of openai you have installed.

**Comment by BartEvers** [comment]
@danielmiessler i am experiencing the same issue. I don't think this is due to the OpenAI version installed? It is regarding the JWT token from the API (fabric_api_server.py) when I try to login.

Can you please provide a solution?
