### ISSUE TITLE
[Bug]: Cannot run pipx install

### ISSUE THREAD

**Issue by alonsoir** [danielmiessler/fabric#284]
### What happened?

I was running pipx install command in root folder, and that ouput happens. Using latest 14.4 (23E214) Sonoma build in OSX.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
┌<▸> ~/g/fabric
└➤
pipx install .
Traceback (most recent call last):
  File "/usr/local/bin/pipx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/main.py", line 921, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/main.py", line 219, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/commands/install.py", line 43, in install
    package_name_from_spec(package_spec, python, pip_args=pip_args, verbose=verbose)
  File "/usr/local/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/commands/common.py", line 380, in package_name_from_spec
    package_name = venv.install_package_no_deps(package_or_url=package_spec, pip_args=pip_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/venv.py", line 302, in install_package_no_deps
    old_package_set = self.list_installed_packages()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/venv.py", line 384, in list_installed_packages
    pip_list = json.loads(cmd_run.stdout.strip())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by danielmiessler** [comment]
Try to clean up your python env and uninstall and reinstall pipx.
