### ISSUE TITLE
[Bug]: Im getting "UnicodeEncodeError:" when trying to extract_wisdom from yt video in "es" lang

### ISSUE THREAD

**Issue by altahookah** [danielmiessler/fabric#397]
### What happened?

Hi! i was trying to use extract_wisdowm pattern with a youtube video in spannish, this is the command i executed
`(fabric) C:\IA\Fabric\fabric>yt --transcript https://www.youtube.com/watch?v=ZCqDXB_DSAQ --lang es | fabric --stream --pattern extract_wisdom`

and this is the output i get:
![image](https://github.com/danielmiessler/fabric/assets/107110452/3963977f-aaec-454a-829a-78a2ad8a5861)

### Version check

- [X] Yes I was.

### Relevant log output

```shell
(fabric) C:\IA\Fabric\fabric>yt --transcript https://www.youtube.com/watch?v=ZCqDXB_DSAQ --lang es | fabric --stream --pattern extract_wisdom
Traceback (most recent call last):
  File "C:\Users\ivan\anaconda3\envs\fabric\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ivan\anaconda3\envs\fabric\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\ivan\.local\bin\yt.exe\__main__.py", line 7, in <module>
    sys.exit(main_yt())
  File "C:\Users\ivan\pipx\venvs\fabric\lib\site-packages\installer\client\cli\yt.py", line 148, in main
    main_function(args.url, args)
  File "C:\Users\ivan\pipx\venvs\fabric\lib\site-packages\installer\client\cli\yt.py", line 113, in main_function
    print(transcript_text.encode('utf-8').decode('unicode-escape'))
  File "C:\Users\ivan\anaconda3\envs\fabric\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\x89' in position 87812: character maps to <undefined>
Error: Error code: 400 - {'error': "'messages' array must only contain objects with a 'content' field that is not empty."}
Error code: 400 - {'error': "'messages' array must only contain objects with a 'content' field that is not empty."}
```

**Comment by danielmiessler** [comment]
Something Windows related. Should be fixed in upcoming Go version.
