### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'ollama' on mac

### ISSUE THREAD

**Issue by Saolee** [danielmiessler/fabric#443]
### What happened?

I get this error when running any of the fabric commands. Tried installing ollama, but to no avail. That's not a requirement though, or is it? 
```
fabric --listmodels                                                            sauli@HR-20220999
Traceback (most recent call last):
  File "/Users/sauli/Library/Caches/pypoetry/virtualenvs/fabric-eA-XT-PW-py3.12/bin/fabric", line 6, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/sauli/code/fabric/installer/client/cli/fabric.py", line 150, in main
    standalone = Standalone(args, args.pattern)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sauli/code/fabric/installer/client/cli/utils.py", line 56, in __init__
    sorted_gpt_models, ollamaList, claudeList, googleList = self.fetch_available_models()
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sauli/code/fabric/installer/client/cli/utils.py", line 432, in fetch_available_models
    import ollama
ModuleNotFoundError: No module named 'ollama'
```

### Version check

- [x] Yes I was.

**Comment by danielmiessler** [comment]
I would restart your shell and restart Ollama.
