### ISSUE TITLE
[Feature request]: Private media to text

### ISSUE THREAD

**Issue by michaellerickson** [danielmiessler/fabric#573]
### What do you need?

WHAT: Media Extensions .MOV, .HEIC, .MP4, .TIFF, .GIF, and the like
WHERE: External hard drives, USB thumb drives, onprem servers, local environments, etc.

NEED: Can fabric implement WHAT to and fro WHERE for transmuting text; I'll button the community to keep this baby clothed.

**Comment by michaellerickson** [comment]
YT did not like my unlisted video.

```
yt --transcript https://www.youtube.com/watch?v=h4ytdPdqh-o
Traceback (most recent call last):
  File "/home/user/.local/bin/yt", line 8, in <module>
    sys.exit(main_yt())
             ^^^^^^^^^
  File "/home/user/.local/pipx/venvs/fabric/lib/python3.11/site-packages/installer/client/cli/yt.py", line 148, in main
    main_function(args.url, args)
  File "/home/user/.local/pipx/venvs/fabric/lib/python3.11/site-packages/installer/client/cli/yt.py", line 86, in main_function
    duration_iso = video_response["items"][0]["contentDetails"]["duration"]
                   ~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

It's been taken down since. I verified the commands. The following video which is NOT mine works:

```
yt --transcript https://youtube.com/watch?v=uXs-zPc63kM
```

**Comment by ksylvan** [comment]
If the models support it, some of these are already implemented using the `-a` flag (add an attachment to the input for the LLM).

If you have a specific case, please open a new issue. Closing this issue.
