### ISSUE TITLE
[Bug]:  An error after fabric execution.

### ISSUE THREAD

**Issue by razvanab** [danielmiessler/fabric#671]
### What happened?

PS H:\DEV\REPOS\LLMs\fabric> fabric --pattern ai
Enter Question: hello
Hello there! How can I assist you today?
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000180A2822A70>
Traceback (most recent call last):
  File "H:\DEV\Conda\envs\temp\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "H:\DEV\Conda\envs\temp\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "H:\DEV\Conda\envs\temp\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "H:\DEV\Conda\envs\temp\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

### Version check

- [X] Yes I was.

**Comment by ebelious** [comment]
on fedora based bistro this worked for me 

sudo yum install gcc-c++
