### ISSUE TITLE
[Bug]: pipx errors on install

### ISSUE THREAD

**Issue by ngmisl** [danielmiessler/fabric#710]
### What happened?

Run 'pipx install .' to begin.
➜  fabric git:(main) pipx install .
Traceback (most recent call last):
  File "/home/local/.local/bin/pipx", line 5, in <module>
    from pipx.main import cli
  File "/home/local/.local/lib/python3.11/site-packages/pipx/main.py", line 19, in <module>
    from packaging.requirements import InvalidRequirement, Requirement
ModuleNotFoundError: No module named 'packaging'

### Version check

- [X] Yes I was.

**Comment by ngmisl** [comment]
local issue
