### ISSUE TITLE
[Bug]: Wsl Fabric Installation

### ISSUE THREAD

**Issue by rex1c** [danielmiessler/fabric#749]
### What happened?

I am unable to install Fabric using `pipx install .` due to the following error message:

* pipx version: "1.0"
* Operating system: "WSL Ubuntu 18"

### Version check

- [X] Yes I was.

### Relevant log output

```shell
ERROR: Command errored out with exit status 1:
   command: /tmp/tmpois1rqv3/bin/python /home/rex1c/.local/pipx/shared/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpyl60vyi9
       cwd: /home/rex1c/fabric
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/home/rex1c/.local/pipx/shared/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/rex1c/.local/pipx/shared/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/rex1c/.local/pipx/shared/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/tmp/pip-build-env-ovg72_bc/overlay/lib/python3.6/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
      poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
    File "/tmp/pip-build-env-ovg72_bc/overlay/lib/python3.6/site-packages/poetry/core/factory.py", line 43, in create_poetry
      raise RuntimeError("The Poetry configuration is invalid:\n" + message)
  RuntimeError: The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)

  ----------------------------------------
WARNING: Discarding file:///home/rex1c/fabric. Command errored out with exit status 1: /tmp/tmpois1rqv3/bin/python /home/rex1c/.local/pipx/shared/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpyl60vyi9 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /tmp/tmpois1rqv3/bin/python /home/rex1c/.local/pipx/shared/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpyl60vyi9 Check the logs for full command output.
Cannot determine package name from spec '/home/rex1c/fabric'. Check package spec for errors.
```

**Comment by michaellerickson** [comment]
Is Ubuntu 18 imperative? It works with `wsl --install --d Ubuntu-24.04`

**Comment by bamit99** [comment]
I think you need to upgraded Poetry. The error you're encountering is due to the use of Poetry's dependency group feature, which was introduced in Poetry 1.2.0. However, it seems the version of Poetry you're using doesn't recognize this syntax.

pip install --upgrade poetry
