### ISSUE TITLE
[Bug]: Minecraft crashed when opening inventory

### ISSUE THREAD

**Issue by Giang336sad** [danielmiessler/fabric#796]
### What happened?

*This bug happen when Im on my own fabric server as soon I open the inventory the game crashed*

### Version check

- [X] Yes I was.

### Relevant log output

```shell
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-08-10 09:51:29
Description: Rendering screen

java.lang.IllegalStateException: Missing element ResourceKey[minecraft:enchantment / veinmining:vein_mining]
	at net.minecraft.class_7871.method_46748(class_7871.java:15)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at net.minecraft.class_7871.method_46747(class_7871.java:15)
	at com.illusivesoulworks.veinmining.client.VeinMiningClientEvents.lambda$tooltip$1(VeinMiningClientEvents.java:93)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.illusivesoulworks.veinmining.client.VeinMiningClientEvents.tooltip(VeinMiningClientEvents.java:93)
	at com.illusivesoulworks.veinmining.client.VeinMiningFabricClientMod.lambda$onInitializeClient$1(VeinMiningFabricClientMod.java:36)
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:35)
	at net.minecraft.class_1799.handler$zki000$fabric-item-api-v1$getTooltip(class_1799.java:2136)
	at net.minecraft.class_1799.method_7950(class_1799.java:807)
	at net.minecraft.class_481.method_51454(class_481.java:801)
	at net.minecraft.class_465.method_2380(class_465.java:182)
	at net.minecraft.class_481.method_25394(class_481.java:790)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$188(class_757.java)
	at net.minecraft.class_757.wrapOperation$bcf000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_7871.method_46748(class_7871.java:15)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at net.minecraft.class_7871.method_46747(class_7871.java:15)
	at com.illusivesoulworks.veinmining.client.VeinMiningClientEvents.lambda$tooltip$1(VeinMiningClientEvents.java:93)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.illusivesoulworks.veinmining.client.VeinMiningClientEvents.tooltip(VeinMiningClientEvents.java:93)
	at com.illusivesoulworks.veinmining.client.VeinMiningFabricClientMod.lambda$onInitializeClient$1(VeinMiningFabricClientMod.java:36)
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:35)
	at net.minecraft.class_1799.handler$zki000$fabric-item-api-v1$getTooltip(class_1799.java:2136)
	at net.minecraft.class_1799.method_7950(class_1799.java:807)
	at net.minecraft.class_481.method_51454(class_481.java:801)
	at net.minecraft.class_465.method_2380(class_465.java:182)
	at net.minecraft.class_481.method_25394(class_481.java:790)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$188(class_757.java)
	at net.minecraft.class_757.wrapOperation$bcf000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (320, 171). Absolute: (960.000000, 513.000000)
	Screen size: Scaled: (640, 343). Absolute: (1920, 1027). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 700.045s
	Wall uptime: 622.744s
	High-res time: 597.902s
	Client ticks: 9614 ticks / 480.700s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['rip_Tengen'/1, l='ClientLevel', x=0.50, y=-60.00, z=0.50]]
	Chunk stats: 1024, 145
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 22813 game time, 22813 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
	Tracked entity count: 1

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, appleskin, balm-fabric, cardinal-components-base, cardinal-components-entity, cloth-config, codec-config-api, craftable_enchanted_golden_apple, easyanvils, easymagic, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgeconfigapiport, fpsdisplay, grindenchantments, guardvillagers, inventoryhud, iteminteractions, jei, midnightlib, nvidium, polytone, repurposed_structures, sodium, spectrelib, trinkets, veinmining, waystones, worldedit, xaerominimap, xaeroworldmap, file/Fullbright-SP-1.21.zip, file/enchant icons 1.21 v1.3.zip, file/xali's Enhanced Vanilla -1.11.2b-rev.54d51d4.zip, file/xali's Enchanted Books Addon v3 1.21.zip, file/Default-Dark-Mode-1.20.2+-2024.6.0.zip, easyanvils:default_block_models

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 236836864 bytes (225 MiB) / 2304770048 bytes (2198 MiB) up to 4227858432 bytes (4032 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.101.2111
	Graphics card #1 name: NVIDIA GeForce MX130
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 2048.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.6081
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: Unknown
	Virtual memory max (MiB): 14718.22
	Virtual memory used (MiB): 11811.64
	Swap memory total (MiB): 6656.00
	Swap memory used (MiB): 1189.99
	Space in storage for jna.tmpdir (MiB): available: 48179.82, total: 121349.35
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 48179.82, total: 121349.35
	Space in storage for io.netty.native.workdir (MiB): available: 48179.82, total: 121349.35
	Space in storage for java.io.tmpdir (MiB): available: 48179.82, total: 121349.35
	Space in storage for workdir (MiB): available: 48179.82, total: 121349.35
	JVM Flags: 4 total; -Xmx4096m -Xms256m -Xmx4031m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		appleskin: AppleSkin 3.0.5+mc1.21
			cloth-config: Cloth Config v15 15.0.127
				cloth-basic-math: cloth-basic-math 0.6.1
		balm-fabric: Balm 21.0.14
			kuma_api: KumaAPI 21.0.4
		collective: Collective 7.81
		craftable_enchanted_golden_apple: Craftable Enchanted Golden Apple 1.0.7
		doubledoors: Double Doors 5.9
		easyanvils: Easy Anvils 21.0.3
		easymagic: Easy Magic 21.0.2
		easyshulkerboxes: Easy Shulker Boxes 21.0.2
			iteminteractions: Item Interactions 21.0.4
		elytraslot: Elytra Slot 9.0.0+1.21
			mixinsquared: MixinSquared 0.1.2-beta.6
		enchantingcommands: Enchanting Commands 3.4
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabricloader: Fabric Loader 0.16.0
			mixinextras: MixinExtras 0.4.0
		forgeconfigapiport: Forge Config API Port 21.0.8
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		fpsdisplay: FPS-Display 4.2.0+1.21
		grindenchantments: Grind Enchantments 3.2.2+1.21-rc1
			codec-config-api: Codec config API 2.0.0+1.20.5-rc3
		guardvillagers: GuardVillagers 2.1.2-1.21
		infinitetrading: Infinite Trading 4.5
		inventoryhud: Inventory HUD + 3.4.24
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.8.2.99
		midnightlib: MidnightLib 1.5.7
		minecraft: Minecraft 1.21
		mousetweaks: Mouse Tweaks 2.26
		nvidium: Nvidium 0.2.9-beta
		pickupnotifier: Pick Up Notifier 21.0.0
		polytone: Polytone 1.21-2.3.0
			net_objecthunter_exp4j: exp4j 0.4.8
		puzzleslib: Puzzles Lib 21.0.19
		repurposed_structures: Repurposed Structures 7.5.4+1.21-fabric
		sodium: Sodium 0.5.11+mc1.21
		trinkets: Trinkets 3.10.0
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
		veinmining: Vein Mining 5.0.0-beta+1.21
			spectrelib: SpectreLib 0.17.1+1.21
		waystones: Waystones 21.0.8
		worldedit: WorldEdit 7.3.5+6880-8ba3d89
		xaerominimap: Xaero's Minimap 24.2.1
		xaeroworldmap: Xaero's World Map 1.38.8
	Launched Version: fabric-loader-0.16.0-1.21
	Launcher name: java-minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce MX130/PCIe/SSE2 GL version 3.2.0 NVIDIA 560.81, NVIDIA Corporation
	Window size: 1920x1027
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fast
	Render Distance: 5/5 chunks
	Resource Packs: vanilla, fabric, appleskin (incompatible), balm-fabric (incompatible), cardinal-components-base, cardinal-components-entity, cloth-config, codec-config-api, craftable_enchanted_golden_apple, easyanvils, easymagic, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgeconfigapiport, fpsdisplay, grindenchantments, guardvillagers, inventoryhud, iteminteractions, jei (incompatible), midnightlib, nvidium, polytone, repurposed_structures, sodium, spectrelib (incompatible), trinkets, veinmining (incompatible), waystones (incompatible), worldedit (incompatible), xaerominimap (incompatible), xaeroworldmap (incompatible), file/Fullbright-SP-1.21.zip, file/enchant icons 1.21 v1.3.zip, file/xali's Enhanced Vanilla -1.11.2b-rev.54d51d4.zip, file/xali's Enchanted Books Addon v3 1.21.zip, file/Default-Dark-Mode-1.20.2+-2024.6.0.zip, easyanvils:default_block_models
	Current Language: vi_vn
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
```

**Comment by kcoderhtml** [comment]
umm this isn't minecraft?

**Comment by fonteijne** [comment]
@Giang336sad this is something for https://github.com/FabricMC  ;-)

**Comment by kcoderhtml** [comment]
Thanks @fonteijne I came back to the issue this morning because I relied I’d forgotten to link to the correct fabric but you had already done it :) @Giang336sad this repo is for a command line ai tool that strings together prompts and llm through piping commands together. It’s actually really awesome!
