### ISSUE TITLE
Import error (missing utils)

### ISSUE THREAD

**Issue by jeremi** [danielmiessler/fabric#89]
It seems some files are missing from the CLI. 

https://github.com/danielmiessler/fabric/blob/main/client/fabric/fabric.py#L1C1-L1C44

there is no utils package I could find.

**Comment by lmccay** [comment]
@jeremi - there is a utils.py in the same location.
I ran into this as well.
Once I got my python version to 3.11 (and made sure python3 was used) AND used "poetry shell" it worked its way out.
Not entirely sure which fixed that.

**Comment by jeremi** [comment]
I'm on 3.11 as well:
```
 python --version
Python 3.11.7
```

it work when I directly run the .py:
```
❯ python fabric.py
Please run --setup to set up your API key and download patterns.
~/Projects/138-ai/fabric/client/fabric main                                                                                                                                                       fabric-jCrqo8r--py3.11 11:18:44
❯ fabric
Traceback (most recent call last):
  File "/Users/jeremi/Library/Caches/pypoetry/virtualenvs/fabric-jCrqo8r--py3.11/bin/fabric", line 3, in <module>
    from fabric import main
  File "/Users/jeremi/Projects/138-ai/fabric/client/fabric/__init__.py", line 1, in <module>
    from .fabric import main
  File "/Users/jeremi/Projects/138-ai/fabric/client/fabric/fabric.py", line 1, in <module>
    from utils import Standalone, Update, Setup
ModuleNotFoundError: No module named 'utils'
~/Projects/138-ai/fabric/client/fabric main                                                                                                                                                       fabric-jCrqo8r--py3.11 11:18:48
❯ \fabric
Traceback (most recent call last):
  File "/Users/jeremi/Library/Caches/pypoetry/virtualenvs/fabric-jCrqo8r--py3.11/bin/fabric", line 3, in <module>
    from fabric import main
  File "/Users/jeremi/Projects/138-ai/fabric/client/fabric/__init__.py", line 1, in <module>
    from .fabric import main
  File "/Users/jeremi/Projects/138-ai/fabric/client/fabric/fabric.py", line 1, in <module>
    from utils import Standalone, Update, Setup
ModuleNotFoundError: No module named 'utils'
~/Projects/138-ai/fabric/client/fabric main                                                                                                                                                       fabric-jCrqo8r--py3.11 11:18:56
❯
```

**Comment by danielmiessler** [comment]
We're fixing this soon, thank you.
